### ISSUE TITLE
Add README section about USE_PGXS=1 param

### ISSUE THREAD

**Issue by fernandomantoan** [pgEdge/snowflake-sequences#1]
I was trying to build this extension without having Postgres source files, after some digging I saw that by running the `make` command with the `USE_PGXS=1` argument I could build the snowflake extension with the existing `pg_config` command installed. It would be nice if you can include this argument in the `README.md` section.

**Comment by luss** [comment]
I updated the README https://github.com/pgEdge/snowflake-sequences/commit/54a721d06b74727e5911c95fd0c94a166511be7e
